# Generated by Django 3.2.15 on 2022-11-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
